# Generated by Django 2.1.8 on 2019-05-22 20:21

import acm_placement_app.placements.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('school_data_file', models.FileField(upload_to='data/inputs/school_data/')),
                ('acm_survey_data_file', models.FileField(upload_to='data/inputs/acm_survey_data/')),
                ('num_iterations', models.IntegerField(default=10000, help_text='The number of team placements that will be attempted. 10,000 or more is recommended.', verbose_name='Number of iterations')),
                ('prevent_roommates', models.BooleanField(default=True, verbose_name='Prevent roommates from serving on the same team?')),
                ('consider_HS_elig', models.BooleanField(default=True, help_text='ACMs are eligible to serve in High School if they are 21+ years old (or have college experience) and are confident tutoring at least algebra-level math.', verbose_name='Apply High School eligibility rule?')),
                ('calc_commutes', models.BooleanField(default=True, help_text='Commute calculations cost HQ a small amount and take time to complete. For 100 ACMs and 10 schools, the cost is $5 and takes about 10 minutes.', verbose_name='Calculate commutes?')),
                ('commute_date', models.DateField(blank=True, default=acm_placement_app.placements.models.get_tomorrow_date, help_text='Required if calculating commutes. Choose a date that represents normal traffic.', verbose_name='Travel date for commute calculations')),
                ('commutes_reference', models.FileField(blank=True, help_text="After placements are made, you will find a 'Output_Commute_Reference.csv' file in the results. If you want to run additional placement processes, upload that file here to avoid commute calculation wait time and cost.", upload_to='documents/outputs')),
                ('commute_factor', models.IntegerField(default=1, verbose_name='Importance of commute')),
                ('ethnicity_factor', models.IntegerField(default=1, verbose_name='Importance of ethnic diversity')),
                ('gender_factor', models.IntegerField(default=1, verbose_name='Importance of gender diversity')),
                ('edscore_factor', models.IntegerField(default=1, verbose_name='Importance of educational attainment diversity')),
                ('spanish_factor', models.IntegerField(default=1, verbose_name='Importance of matching Spanish speaker targets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
