# Generated by Django 2.1.8 on 2019-05-29 05:15

import acm_placement_app.placements.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commutes_file', models.FileField(upload_to=acm_placement_app.placements.models.output_upload_path)),
                ('placements_file', models.FileField(upload_to=acm_placement_app.placements.models.output_upload_path)),
                ('trace_file', models.FileField(upload_to=acm_placement_app.placements.models.output_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='placementrequest',
            name='acm_survey_data_file',
            field=models.FileField(upload_to=acm_placement_app.placements.models.input_upload_path, verbose_name='ACM survey data file'),
        ),
        migrations.AlterField(
            model_name='placementrequest',
            name='commutes_reference_file',
            field=models.FileField(blank=True, help_text="After placements are made, you will find a 'Output_Commute_Reference.csv' file in the results. If you want to run additional placement processes, upload that file here to avoid commute calculation wait time and cost.", upload_to=acm_placement_app.placements.models.input_upload_path),
        ),
        migrations.AlterField(
            model_name='placementrequest',
            name='school_data_file',
            field=models.FileField(upload_to=acm_placement_app.placements.models.input_upload_path),
        ),
        migrations.AddField(
            model_name='placementresult',
            name='placementrequest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placements.PlacementRequest'),
        ),
    ]
