# Generated by Django 2.1.8 on 2019-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_auto_20190529_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='placementrequest',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
