# Generated by Django 2.1.8 on 2019-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_auto_20190523_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementsrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
