# Generated by Django 2.1.8 on 2019-05-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_auto_20190529_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementrequest',
            old_name='completed',
            new_name='started',
        ),
    ]
