# Generated by Django 2.1.8 on 2019-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_placementsrequest_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementsrequest',
            old_name='commutes_reference',
            new_name='commutes_reference_file',
        ),
        migrations.AddField(
            model_name='placementsrequest',
            name='errors',
            field=models.TextField(blank=True),
        ),
    ]
